site_name: Συλλέκτης δεδομένων από το Twitter
pages:
- Αρχική σελίδα: index.md
- Παράδειγμα χρήσης: Παράδειγμα/Παράδειγμα-χρήσης.md
- Οι λογαριασμοί: Παράδειγμα/Λογαριασμοί.md
- Ανάλυση συναισθήματος: Παράδειγμα/Ανάλυση-συναισθήματος.md
- Tweets και χρόνος: Παράδειγμα/Tweets-και-χρόνος.md
- Συναίσθημα σε σχέση με το χρόνο: Παράδειγμα/Συναίσθημα-σε-σχέση-με-το-χρόνο.md
- Συναίσθημα και δημοτικότητα: Παράδειγμα/Συναίσθημα-και-δημοτικότητα.md
- Κατέβασμα: download.md
- Bugs: bugs.md
- Credits: credits.md
- License: LICENSE.md
theme: readthedocs
extra_css: [extra.css]
site_favicon: favicon.ico