site_name: Συλλέκτης δεδομένων από το Twitter
pages:
- Αρχική: index.md
- Παράδειγμα: Παράδειγμα/README.md
- Ανάλυση: Παράδειγμα/README2.md
- Acknowledgements: /../acknowledgements.md
- License: /../LICENSE.md
theme: readthedocs
extra_css: [extra.css]